name: Test Project

on: 
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    image: node:20
  steps:
    - uses: actions/checkout@v3
      with: 
        node-versions: 20
    - run: npm ci 
    - run: npm test
    - run: npm run build 
    
